juntagrico_badges/urls.py
from django.urls import path
from juntagrico_badges import views, views_admin

app_name = 'jbg'
urlpatterns = [
    path('jbg/home/', views.home, name='home'),
    path('jbg/add/<int:badge_id>/', views.add_badge, name='add-badge'),
    path('jbg/remove/<int:badge_id>/', views.remove_badge, name='remove-badge'),

    # admin
    path('jbg/admin/memberslist/', views_admin.members_list, name='admin-memberslist')
]

juntagrico_badges/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from juntagrico.view_decorators import highlighted_menu

from juntagrico_badges.entity.badges import Badge


@login_required
@highlighted_menu('badges')
def home(request):
    renderdict = {
        'badges': Badge.objects.filter(members=request.user.member),
        'available_badges': Badge.objects.filter(self_assignable=True).exclude(members=request.user.member)
    }
    return render(request, "jbg/home.html", renderdict)


@login_required
def add_badge(request, badge_id):
    badge = get_object_or_404(Badge, id=badge_id)
    if badge.self_assignable:
        member = request.user.member
        member.badges.add(badge)
        member.save()
    return redirect('jbg:home')


@login_required
def remove_badge(request, badge_id):
    badge = get_object_or_404(Badge, id=badge_id)
    if badge.self_assignable:
        member = request.user.member
        member.badges.remove(badge)
        member.save()
    return redirect('jbg:home')

juntagrico_badges/templates/jbg/home.html
{% extends "base.html" %}
{% load juntagrico.config %}
{% load i18n static %}
{% block page_title %}
    <h3>{% translate "Abzeichen" %}</h3>
{% endblock %}

{% block content %}
    <h4>{% translate "Deine Abzeichen" %}</h4>
        <div class="row">
            {% for badge in badges %}
                {% include 'jbg/snippets/badge.html' with badge=badge %}
            {% endfor %}
        </div>
    <h4>{% translate "Abzeichen hinzufügen" %}</h4>
        <div class="row">
            {% for available_badge in available_badges %}
                {% include 'jbg/snippets/badge.html' with badge=available_badge %}
            {% endfor %}
        </div>
{% endblock %}

{% block styles %}
    <link href="{% static "jbg/css/badge.css" %}" rel="stylesheet"/>
{% endblock %}

juntagrico_badges/templates/jbg/management_lists/badges.html
{% extends "juntagrico/manage/base.html" %}
{% load i18n %}
{% load juntagrico.common %}
{% load juntagrico.config %}

{% block page_title %}
    <h3>
        {% trans "Abzeichen" %}
    </h3>
{% endblock %}

{% block content %}
    {% include 'juntagrico/manage/member/snippets/toggle_buttons.html' %}
    {{ block.super }}
{% endblock %}

{% block list %}
    <table id="filter-table" class="list table" style="display: table;">
        <thead>
            <tr>
                <th class="filter">
                    {% trans "Mitglied" %}
                </th>
                <th class="filter">
                    {% trans "Abzeichen" %}
                </th>
            </tr>
        </thead>
        <tbody>
            {% for member in management_list %}
                <tr>
                    <td>
                        {% include 'juntagrico/manage/member/snippets/display_linked.html' %}
                    </td>
                    <td>
                        {% for badge in member.badges.all %}
                            {{ badge.name }}{% if not forloop.last %},{% endif %}
                        {% endfor %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

juntagrico_badges/templates/jbg/snippets/badge.html
{% load i18n %}
<div class="col-md-4">
    <div class="jbg-badge jbg-badge-{{ badge.id }}">
        <h5 class="jbg-badge-title">{{ badge.name }}</h5>
        <p>{{ badge.description }}</p>
        {% if badge.self_assignable %}
            {% if request.user.member in badge.members.all %}
                <p><a href="{% url 'jbg:remove-badge' badge.id %}">{% translate "entfernen" %}</a></p>
            {% else %}
                <p><a href="{% url 'jbg:add-badge' badge.id %}">{% translate "hinzufügen" %}</a></p>
            {% endif %}
        {% endif %}
    </div>
</div>

juntagrico_badges/templates/juntagrico/menu/admin.html
{% extends "juntagrico/menu/admin.html" %}
{% load i18n %}
{% load juntagrico.config %}
{% block extend %}
    {% if perms.juntagrico.can_view_badges %}
        {% vocabulary "member_pl" as v_member_pl %}
        <li class="nav-item">
            <a class="nav-link{% if 'admin-memberslist' not in request.resolver_match.url_name %} collapsed{% endif %}"
               data-toggle="collapse" href="#badge">
                <i class="bi bi-caret-down turn"></i>
                {% trans "Abzeichen" %}
            </a>
            <div class="collapse{% if 'admin-memberslist' in request.resolver_match.url_name %} show{% endif %}" id="badge">
                <ul class="nav flex-column admin-menu subadmin-menu">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'jbg:admin-memberslist' %}">
                            {{ v_member_pl }}
                        </a>
                    </li>
                </ul>
            </div>
        </li>
    {% endif %}
    {{ block.super }}
{% endblock %}

juntagrico_badges/templates/juntagrico/menu/user.html
{% extends "juntagrico/menu/user.html" %}
{% load i18n %}
{% load juntagrico.common %}
{% load juntagrico.config %}
{% block extend %}
    <li class="nav-item">
        <a class="nav-link {{ request|activemenu:"badges" }}" href="{% url 'jbg:home' %}">{% translate "Abzeichen" %}</a>
    </li>
    {{ block.super }}
{% endblock %}